# Welcome to Jekyll!
#

# Site settings
title: BME Suborbitals
description: |
  The first Hungarian rocketry team by university students!
owner: BME Suborbitals # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: bme.suborbitals@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  linkedin-square: https://hu.linkedin.com/company/bmesuborbitals
  facebook-official: https://www.facebook.com/Suborbitals.BME
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: bme.suborbitals@gmail.com
  #flickr:
  instagram: https://www.instagram.com/bmesuborbitals
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
